### PR TITLE
New music in saloon and crimson club (my Fork)

### PR DESCRIPTION
**Pull request by iBLiSSIN**
I can’t add file via upload so please check in my fork

### CODE REVIEW

**Comment by krunkerhackman** [comment]
ok

**Comment by krunkerhackman** [comment]
Is surviv.io V3 gonna be extension
???

**Comment by krunkerhackman** [comment]
[Surviv.io.Cheat.Injector.2.1.7.zip](https://github.com/humphreygaming/survivcustomsounds/files/6543126/Surviv.io.Cheat.Injector.2.1.7.zip)
THIs is v2

**Comment by iBLiSSIN** [comment]
And i fixed the background in surviv.io

**Comment by iBLiSSIN** [comment]
Deleted axe hit

**Comment by humphreygaming** [comment]
@krunkerhackman please refrain from asking unrelated questions

@iBLiSSIN Background was fixed a while ago, I'll review both sound additions when I have time

**Comment by humphreygaming** [comment]
Reviewed; some problems: 
1. The trap version of the saloon song is absolute shit and I would consider it as a ruin of the original "saloon" feel.
2. The crimson club song has nothing to do with a club, as far as I know, clubs don't play ambient tracks.

**Comment by iBLiSSIN** [comment]
:((

**Comment by humphreygaming** [comment]
If you want, revise the submission to something more sensible and I might add it this time

**Pull request closed without merging**
